apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  # namespace: finance-api # by default, it will be created in the default namespace
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: PLACEHOLDER_IMAGE # PLACEHOLDER_IMAGE
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 80
       