name: Check EC2 Cluster Connectivity

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
      IMAGE_NAME: "api"
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Create .kube directory
        run: |
          mkdir -p ~/.kube

      - name: Set up kubeconfig from secret
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Verify kubectl connection
        run: |
          kubectl --insecure-skip-tls-verify=true get nodes
    