name: Check Secrets

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check secret
      run: |
        echo "DOCKER_HUB_REPOSITORY: $DOCKER_HUB_REPOSITORY" 
        echo "DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME" 
        echo "DOCKER_HUB_ACCESS_TOKEN: $DOCKER_HUB_ACCESS_TOKEN" 
        echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID" 
        echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
        echo "AWS_REGION: $AWS_REGION"
      env:
        DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
